### ISSUE TITLE
Documenting Usage / minimal steps

### ISSUE THREAD

**Issue by bdice** [dgasmith/reporec#2]
Hey @dgasmith, I am interested in using this tool! I noticed the docs are empty and the README doesn't have any usage instructions yet.

I exported a `GITHUB_TOKEN` with most of the read-only permissions enabled. I tried running the YAML files in the `examples/` folder but I'm getting a traceback that seems to be from failed authentication.

```
Traceback (most recent call last):
  File "/home/bdice/anaconda3/envs/dice/bin/reporec", line 11, in <module>
    load_entry_point('reporec', 'console_scripts', 'reporec')()
  File "/home/bdice/code/reporec/reporec/cli.py", line 76, in main
    github_df = reporec.github.build_table(username, repository, old_data=github_df)
  File "/home/bdice/code/reporec/reporec/github.py", line 49, in build_table
    view = pd.DataFrame(get_views(org, repo))
  File "/home/bdice/code/reporec/reporec/github.py", line 37, in get_views
    return get_api("repos", org, repo, "traffic", "views")[0]["views"]
  File "/home/bdice/code/reporec/reporec/github.py", line 29, in get_api
    r.raise_for_status()
  File "/home/bdice/anaconda3/envs/dice/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/psi4/psi4/traffic/views
```

I'm happy to contribute a basic usage description via a PR, here is what I have so far (but it's not working). If you can point me to what I'm missing, I'll update this with working instructions. The statistics from `conda` are already working fine without any authentication.

## Usage (draft)

1. Write a YAML file `yourrepos.yaml` using the same format as the files in `examples/`. Currently `reporec` can access statistics from GitHub repositories and conda packages.
2. If you need access to GitHub statistics, get a GitHub API [Personal Access token](https://github.com/settings/tokens). `reporec` requires permissions to read from public (and/or private) repositories. Export the GitHub API token to your shell environment with `export GITHUB_TOKEN=<your token here>`
3. Run `reporec yourrepos.yaml` to generate reports. A directory `rrdata` will be created with reports output in CSV format.

**Comment by dgasmith** [comment]
Hey, cool! So this started out as something pretty hacky and I haven't had too much time to work on it. 

If I remember correctly GitHub views requires full repo access. My token is the following:
```
 repo  Full control of private repositories
  repo:status  Access commit status
  repo_deployment  Access deployment status
  public_repo  Access public repositories
  repo:invite  
```

Ah, ok so I have a private token on Travis so that the tests pass and you are trying to access the project psi4/psi4 which you do not have access to which is why you are getting the forbidden error.

**Comment by dgasmith** [comment]
I made you a collaborator on this. I think we will eventually move this into the main MolSSI repository set and make something official. For now feel free to go wild.

**Comment by bdice** [comment]
@dgasmith Thanks!
